{{ $files := .Files }}
{{ range tuple "inflation" "happiness" }}
{{ $name := printf "postgresql-%s-datasource" . }}
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ $name }}
  namespace: grafana
  labels:
    app: grafana
spec:
  name: {{ $name }}
  datasources:
  - name: {{ $name }}
    type: postgres
    database: {{ . }}
    editable: false
    jsonData:
      connMaxLifetime: 14400
      maxIdleConns: 2
      maxOpenConns: 0
      postgresVersion: 1400
      sslmode: disable
      timescaledb: false
    user: grafana_reader # user to access your database
    secureJsonData:
      password: {{ $files.Get "secrets/grafana-reader-pass"}} # Symlink
    url: data-workshop-postgresql.postgres:5432 #change to url of your postgres instance
---
{{ end }}
