{
 "title": "Single country happiness",
 "description": "Happiness stats for a single country",
 "time": { "from": "2014-12-31T22:00:00.000Z", "to": "2019-01-01T21:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "country_or_region",
    "label": "Country or Regioi",
    "query": "SELECT DISTINCT \"country_or_region\" FROM raw.years_all"
   },
   {
    "name": "happiness_metrics",
    "label": "Happiness metrics",
    "query": "SELECT *\nFROM\n(\n\tVALUES\n\t\t('GDP per Capita', 'gdp_per_capita'),\n\t\t('Family', 'family'),\n                ('Life Expectancy', 'life_expectancy'),\n                ('Freedom', 'freedom'),\n                ('Government Corruption', 'government_corruption'),\n                ('Generosity', 'generosity'),\n\t\t('Dystopia Residual', 'dystopia_residual')\n) AS t (__text, __value)"
   }
  ]
 },
 "panels": [
  {
   "title": "$country_or_region Happiness Stats",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  *\r\nFROM (\r\n  SELECT \r\n    to_date(\"year\"::TEXT, 'YYYY') AS \"ts\", \r\n    ${happiness_metrics:doublequote}\r\n  FROM raw.years_all \r\n  WHERE \r\n    country_or_region = '$country_or_region'\r\n  ORDER \r\n    BY \"ts\"\r\n) AS s1\r\nWHERE\r\n  $__timeFilter(\"ts\")"
    }
   ]
  },
  {
   "title": "$country_or_region Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  to_date(\"year\"::TEXT, 'YYYY') as \"time\",\r\n  \"happiness_score\"\r\nFROM raw.years_all \r\nWHERE \r\n  \"country_or_region\" = '$country_or_region'\r\nORDER BY\r\n  \"time\"\r\n;"
    }
   ]
  },
  {
   "title": "$country_or_region Ranking",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  to_date(\"year\"::TEXT, 'YYYY') AS \"time\",\r\n  \"happiness_rank\",\r\n  \"happiness_score\"\r\nFROM raw.years_all \r\nWHERE \r\n  \"country_or_region\" = '$country_or_region'\r\nORDER BY\r\n  \"time\"\r\n;\r\n  "
    }
   ]
  },
  {
   "title": "$country_or_region Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT \r\n  *\r\nFROM (\r\n  SELECT \r\n    to_date(\"year\"::TEXT, 'YYYY') AS \"ts\",\r\n    ${happiness_metrics:doublequote}\r\n  FROM raw.years_all \r\n  WHERE\r\n    country_or_region = '$country_or_region'\r\n  ORDER \r\n    BY year\r\n) AS s1\r\nWHERE\r\n  $__timeFilter(\"ts\")\r\n  ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "$country_or_region Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  \"year\",\r\n  ${happiness_metrics:doublequote}\r\nFROM (\r\n  SELECT \r\n    to_date(\"year\"::TEXT, 'YYYY') AS \"ts\",\r\n    \"year\",\r\n    ${happiness_metrics:doublequote}\r\n  FROM raw.years_all \r\n  WHERE\r\n    country_or_region = '$country_or_region'\r\n  ORDER \r\n    BY year\r\n) AS s1\r\nWHERE\r\n  $__timeFilter(\"ts\")\r\n  "
    }
   ]
  },
  {
   "title": "$country_or_region Rankings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  *\r\n  -- \"year\",\r\n  -- ${happiness_metrics:doublequote}\r\nFROM (\r\n  SELECT \r\n    -- \"year\",\r\n    to_date(\"year\"::TEXT, 'YYYY') AS \"ts\",\r\n    ${happiness_metrics:doublequote}\r\n  FROM raw.countries_yearly_rankings() \r\n  WHERE \r\n    country_or_region = '$country_or_region'\r\n) AS s\r\nWHERE\r\n  $__timeFilter(\"ts\") \r\n  "
    }
   ]
  },
  {
   "title": "$country_or_region Rankings Transformed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  *\r\n  -- \"year\",\r\n  -- ${happiness_metrics:doublequote}\r\nFROM (\r\n  SELECT \r\n    -- \"year\",\r\n    to_date(\"year\"::TEXT, 'YYYY') AS \"ts\",\r\n    ${happiness_metrics:doublequote}\r\n  FROM raw.countries_yearly_rankings() \r\n  WHERE \r\n    country_or_region = '$country_or_region'\r\n) AS s\r\nWHERE\r\n  $__timeFilter(\"ts\") \r\n  "
    }
   ]
  }
 ]
}