apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: grafana-operator
    repository: https://charts.bitnami.com/bitnami
    version: 2.7.13
